homeassistant:
  latitude: !secret lat 
  longitude: !secret long 
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks
     trusted_networks:
       - 192.168.1.10/32
   - type: homeassistant
  whitelist_external_dirs:
    - /config/video

http:
  base_url: https://hass.uberserver.nl

cloud:
  google_actions:
    filter:
      include_entities:
        - light.hallway_3
        - light.outdoor_light
        - light.kitchen_ledstrip
        - light.window_light
        - light.rode_lamp
        - light.tradfri_bulb_e27_w_opal_1000lm_2
        - input_boolean.bedtime
        - switch.sonoff_basic_relay_2
        - switch.tradfri_outlet
        - climate.tesla_model_s_5yjsa7e28gf140866_hvac_climate_system


history: 
  exclude:
    domains:
      - automation
      - weblink

stream:
system_health:

frontend:
  themes: !include themes.yaml

discovery:

notify:
  - name: "Pushbullet 1"
    platform: pushbullet
    api_key: !secret pushapi
  - name: "Pushbullet 2"
    platform: pushbullet
    api_key: !secret pushapi2
  - name: telegram_bot
    platform: telegram
    chat_id: !secret telegram_chat_id

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids: !secret telegram_id

sun:
logbook: 
config:

influxdb:
  host: 192.168.1.80

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

evohome:
  username: !secret honeywell_user
  password: !secret honeywell_pass
  scan_interval: 600

rflink:
  port: /dev/ttyUSB0

map:

tts:
  - platform: google_translate
    service_name: google_say

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret aqara_password

vacuum:
  - platform: xiaomi_miio
    name: miep
    host: 192.168.1.34
    token: !secret miiotoken

octoprint:
    host: 192.168.1.75
    api_key: !secret octo-api

ffmpeg:
lovelace:

input_number:
  falcon_animation_speed:
    name: Falcon Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

  kossel_animation_speed:
    name: Kossel Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

media_player:
  - platform: spotify
    client_id: !secret spotify_client 
    client_secret: !secret spotify

cover: !include_dir_merge_list covers

camera: !include_dir_merge_list camera

image_processing:
  - platform: tensorflow
    scan_interval: 10000
    source:
      - entity_id: camera.voordeur
      - entity_id: camera.zijdeur
    file_out:
      - "/config/video/{{ camera_entity.split('.')[1] }}_latest.jpg"
#      - "/config/video/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: "/config/tensorflow/frozen_inference_graph.pb"

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
     
light: !include_dir_merge_list lights

sensor: !include_dir_merge_list sensors

input_boolean: 
  bedtime:
    name: it's bedtime
    initial: off 
    icon: mdi:bed  
  alarm:
    name: alarm
    initial: off
    icon: mdi:alarm

googlehome:
  devices:
    - host: 192.168.1.15
      track_alarms: true
    - host: 192.168.1.16
      track_alarms: true

weather:
  - platform: darksky
    api_key: !secret darksky

logger:
  default: error
  logs:
    homeassistant.components.image_processing: debug

group: !include groups.yaml
automation: !include automations.yaml

script: !include scripts.yaml
