homeassistant:
  latitude: !secret lat 
  longitude: !secret long 
  elevation: 430
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks
     trusted_networks:
       - 192.168.1.10/32
   - type: homeassistant
  whitelist_external_dirs:
    - /config/video

recorder: 
  db_url: !secret database
  purge_keep_days: 50

http:
  cors_allowed_origins:
    - https://cast.home-assistant.io

cloud:


history: 
  exclude:
    domains:
      - automation
      - weblink

stream:
system_health:

frontend:
  javascript_version: latest
  themes: !include themes.yaml

discovery:

notify:
  - name: telegram_bot
    platform: telegram
    chat_id: !secret telegram_chat_id

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids: !secret telegram_id

wake_on_lan:

sun:
logbook: 
config:

influxdb:
  host: 192.168.1.80

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

evohome:
  username: !secret honeywell_user
  password: !secret honeywell_pass
  scan_interval: 600

rflink:
  port: /dev/ttyUSB0

map:

tts:
  - platform: google_translate
    service_name: google_say

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret aqara_password

vacuum:
  - platform: xiaomi_miio
    name: miep
    host: 192.168.1.34
    token: !secret miiotoken

octoprint:
    host: 192.168.1.75
    api_key: !secret octo-api

ffmpeg:
lovelace:

input_select:
  sean_room_location:
    name: Pim's Room Location
    options:
      - Bathroom
      - Office
      - Away
      - Home

input_number:
  stepper_control:
    name: Stepper Control
    initial: 0
    min: -1000
    max: 1000
    step: 1
    mode: slider
  falcon_animation_speed:
    name: Falcon Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10


  kossel_animation_speed:
    name: Kossel Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

media_player:
  - platform: spotify
    client_id: !secret spotify_client 
    client_secret: !secret spotify
    #  - platform: androidtv
    #    name: Livingroom
    #    host: 192.168.1.103
    #    adbkey: /config/adbkey

cover: !include_dir_merge_list covers

camera: !include_dir_merge_list camera

image_processing:
  - platform: tensorflow
    scan_interval: 10000
    source:
#      - entity_id: camera.voordeur
      - entity_id: camera.schuur
      - entity_id: camera.zijdeur
    file_out:
      - "/config/video/{{ camera_entity.split('.')[1] }}_latest.jpg"
#      - "/config/video/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: "/config/tensorflow/frozen_inference_graph.pb"
      categories:
        - person
        - cat
        - car
        - dog
  - platform: tensorflow
    scan_interval: 10000
    source:
      - entity_id: camera.voordeur
    file_out:
      - "/config/video/{{ camera_entity.split('.')[1] }}_latest.jpg"
#      - "/config/video/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: "/config/tensorflow/frozen_inference_graph.pb"
      categories:
        - person
        - cat
        - car
        - dog
      area: 
        top: 0.3

surepetcare:
  username: !secret surepet_user
  password: !secret surepet_pass
  household_id: !secret surepet_household
  flaps: [{id: 209692, name: Tuin}]
  pets: [{id: 52825, name: Wolfje}]

tesla:
  username: !secret tesla_username
  password: !secret tesla_password
     
light: !include_dir_merge_list lights

sensor: !include_dir_merge_list sensors

switch:
  - platform: wake_on_lan
    mac_address: "70:85:c2:6c:44:f3"
    host: 192.168.1.11

input_boolean: 
  bedtime:
    name: it's bedtime
    initial: off 
    icon: mdi:bed  
  pim_present:
    name: Pim Presence
    initial: on
    
hacs:
  token: !secret hacstoken


weather:
  - platform: darksky
    api_key: !secret darksky
    
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_pin
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

#logger:
#  default: error
#  logs:
#    homeassistant.components.image_processing: debug

group: !include groups.yaml
automation: !include automations.yaml

script: !include scripts.yaml
